### ISSUE TITLE
在OSX下不能启动

### ISSUE THREAD

**Issue by jnuc093** [itliusir/xxl-job-admin#1]
➜  xxl-job-admin git:(master) chmod u+x ./mvnw
➜  xxl-job-admin git:(master) ✗ ./mvnw
/Volumes/Macintosh HD/github/xxl-job-admin
错误: 找不到或无法加载主类 org.apache.maven.wrapper.MavenWrapperMain

**Comment by itliusir** [comment]
你好，maven环境正常么？

**Comment by jnuc093** [comment]
正常。

➜  xxl-job-admin git:(master) ✗ ./mvnw
/Volumes/Macintosh HD/github/xxl-job-admin
错误: 找不到或无法加载主类 org.apache.maven.wrapper.MavenWrapperMain

➜  xxl-job-admin git:(master) ✗ mvn --version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-11T00:41:47+08:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 1.8.0_121, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

**Comment by itliusir** [comment]
请使用mvn spring-boot:run命令试下

**Comment by itliusir** [comment]
你好，请更新下代码重新试试

**Comment by jnuc093** [comment]
➜  xxl-job-admin git:(master) ✗ git pull
remote: Counting objects: 9, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 9 (delta 3), reused 8 (delta 3), pack-reused 1
Unpacking objects: 100% (9/9), done.
From github.com:itliusir/xxl-job-admin
   0cb8518..5900d36  master     -> origin/master
Updating 0cb8518..5900d36
Fast-forward
 .mvn/wrapper/maven-wrapper.jar        | Bin 0 -> 47610 bytes
 .mvn/wrapper/maven-wrapper.properties |   1 +
 pom.xml                               |   2 +-
 3 files changed, 2 insertions(+), 1 deletion(-)
 create mode 100644 .mvn/wrapper/maven-wrapper.jar
 create mode 100644 .mvn/wrapper/maven-wrapper.properties
➜  xxl-job-admin git:(master) ✗ ./mvnw
/Volumes/Macintosh HD/github/xxl-job-admin
Downloading https://repo1.maven.org/maven2/org/apache/maven/apache-maven/3.5.3/apache-maven-3.5.3-bin.zip
...............................................................................................................................................................................................................................................................................................................................................................................................................................................................
Unzipping /Users/qk/.m2/wrapper/dists/apache-maven-3.5.3-bin/2c22a6s60afpuloj4v181qvild/apache-maven-3.5.3-bin.zip to /Users/qk/.m2/wrapper/dists/apache-maven-3.5.3-bin/2c22a6s60afpuloj4v181qvild
Set executable permissions for: /Users/qk/.m2/wrapper/dists/apache-maven-3.5.3-bin/2c22a6s60afpuloj4v181qvild/apache-maven-3.5.3/bin/mvn
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.241 s
[INFO] Finished at: 2018-08-12T10:56:26+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] No goals have been specified for this build. You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoGoalSpecifiedException

**Comment by itliusir** [comment]
./mvnw spring-boot:run

**Comment by jnuc093** [comment]
./mvnw spring-boot:run 可以了
